name: yeedart
description: Simple Dart library that lets you control Yeelight devices over LAN.
version: 0.3.1+2
homepage: https://github.com/janstol/yeedart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.7.0

dev_dependencies:
  lint: ^1.5.3
  mockito: ^5.0.16
  path: ^1.8.0
  test: ^1.17.12
