name: yeedart
description: Simple Dart library that lets you control Yeelight devices over LAN.
version: 0.3.0
homepage: https://github.com/janstol/yeedart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  lint: ^1.5.2
  mockito: ^5.0.0
  path: ^1.8.0
  test: ^1.16.5
